# Generated by Django 4.2.4 on 2023-09-15 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=224)),
                ('nama', models.CharField(max_length=224)),
                ('ket', models.CharField(max_length=224)),
            ],
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=224)),
                ('title', models.CharField(max_length=224)),
                ('header', models.CharField(default='this is header text of content', max_length=224)),
                ('foto', models.FileField(blank=True, upload_to='article')),
                ('jenis', models.IntegerField(choices=[(0, 'news'), (1, 'tips')], default=0)),
                ('text', models.TextField(blank=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('dibaca', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=224)),
                ('kontak', models.CharField(max_length=224)),
                ('text', models.TextField(blank=True)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='this-is-slug', max_length=224)),
                ('photo', models.FileField(default='example.jpg', upload_to='event')),
                ('nama', models.CharField(max_length=224)),
                ('hadiah', models.CharField(max_length=224)),
                ('jenis', models.IntegerField(choices=[(0, 'credit'), (1, 'barang'), (2, 'kelas'), (3, 'jabatan')], default=0)),
                ('sponsor', models.CharField(max_length=224)),
                ('peraturan', models.TextField(blank=True)),
                ('mulai', models.DateField(blank=True, null=True)),
                ('selesai', models.DateField(blank=True, null=True)),
                ('by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Improve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=224)),
                ('why', models.CharField(max_length=224)),
                ('how', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=224, unique=True)),
                ('keterangan', models.CharField(max_length=224)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=224, unique=True)),
                ('keterangan', models.CharField(max_length=224)),
            ],
        ),
        migrations.CreateModel(
            name='LevelAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=224, unique=True)),
                ('keterangan', models.CharField(max_length=224)),
                ('ads', models.BooleanField(default=True)),
                ('vidio', models.BooleanField(default=False)),
                ('nyawa', models.IntegerField(default=0)),
                ('premium', models.BooleanField(default=False)),
                ('biaya', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('promo', models.IntegerField(default=0)),
                ('bestseller', models.BooleanField(default=False)),
                ('meeting', models.IntegerField(default=0)),
                ('isPrivate', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=1)),
                ('mengulang', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=224, unique=True)),
                ('keterangan', models.CharField(max_length=224)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=224)),
                ('potongan', models.IntegerField(default=0)),
                ('by', models.CharField(max_length=224)),
                ('banner', models.CharField(max_length=224)),
            ],
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=224)),
                ('answer', models.CharField(max_length=224)),
                ('klik', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=224)),
                ('sub', models.TextField()),
                ('icon', models.FileField(blank=True, upload_to='landing')),
                ('logo', models.FileField(blank=True, upload_to='landing')),
                ('foto', models.FileField(blank=True, upload_to='landing')),
                ('fotoadv', models.FileField(blank=True, upload_to='landing')),
                ('alamat', models.CharField(blank=True, max_length=224)),
                ('telp', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ig', models.CharField(blank=True, max_length=224)),
                ('fb', models.CharField(blank=True, max_length=224)),
                ('tiktok', models.CharField(blank=True, max_length=224)),
                ('youtube', models.CharField(blank=True, max_length=224)),
                ('komisi_teacher', models.IntegerField(default=70)),
                ('komisi_developer', models.IntegerField(default=7)),
                ('komisi_owner', models.IntegerField(default=23)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=0)),
                ('bulan', models.IntegerField(default=0)),
                ('keluar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/event')),
                ('done', models.BooleanField(default=False)),
                ('S_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_sender', to=settings.AUTH_USER_MODEL)),
                ('eventname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='owner.event')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.IntegerField(choices=[(0, 'report'), (1, 'update')], default=0)),
                ('text', models.TextField(blank=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Earn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField(default=0)),
                ('owner', models.IntegerField(default=0)),
                ('developer', models.IntegerField(default=0)),
                ('tgl', models.DateField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendapatan_user', to='owner.levelakun')),
            ],
        ),
    ]
