# Generated by Django 4.2.6 on 2023-10-19 23:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_langganan_remove_levelakun_ads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schadule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terlaksana', models.BooleanField(default=False)),
                ('time', models.IntegerField(blank=True, choices=[(0, '07:30'), (1, '09:00'), (2, '10:30'), (3, '13:00'), (4, '14:30'), (5, '16:00'), (6, '18:30'), (7, '20:00')], default=1)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_akun_schadule', to='owner.levelakun')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_schadule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Private',
        ),
        migrations.DeleteModel(
            name='UserMentor',
        ),
        migrations.DeleteModel(
            name='UserRoom',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='right',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='wrong',
        ),
        migrations.RemoveField(
            model_name='room',
            name='day',
        ),
        migrations.RemoveField(
            model_name='room',
            name='kuota',
        ),
        migrations.RemoveField(
            model_name='room',
            name='link',
        ),
        migrations.RemoveField(
            model_name='room',
            name='password',
        ),
        migrations.RemoveField(
            model_name='room',
            name='private',
        ),
        migrations.AddField(
            model_name='bab',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kelas_bab', to='teacher.kelas'),
        ),
        migrations.AddField(
            model_name='bab',
            name='rangkuman',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bab',
            name='urutan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='Kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kelas_creator', to='teacher.kelas'),
        ),
        migrations.AddField(
            model_name='creator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='games',
            name='bab_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bab_games', to='teacher.bab'),
        ),
        migrations.AddField(
            model_name='games',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Games_kelas', to='teacher.kelas'),
        ),
        migrations.AddField(
            model_name='games',
            name='pelajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_pelajaran', to='teacher.pelajaran'),
        ),
        migrations.AddField(
            model_name='games',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kelas',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategori_kelas', to='owner.kategori'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_kelas', to='owner.level'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='rangkuman',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelajaran',
            name='bab_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bab_kelas', to='teacher.bab'),
        ),
        migrations.AddField(
            model_name='pelajaran',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kelas_pelajaran', to='teacher.kelas'),
        ),
        migrations.AddField(
            model_name='questions',
            name='bab_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bab_question', to='teacher.bab'),
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_kategori', to='owner.kategori'),
        ),
        migrations.AddField(
            model_name='questions',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_kelas', to='teacher.kelas'),
        ),
        migrations.AddField(
            model_name='questions',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_pelajaran', to='teacher.pelajaran'),
        ),
        migrations.AddField(
            model_name='questions',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_level', to='owner.level'),
        ),
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='jadwal',
            field=models.IntegerField(blank=True, choices=[(0, "senin,  rabu, jum'at"), (1, 'selasa,  kamis, sabtu'), (2, "jum'at,  sabtu, minggu")], default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_akun_room', to='owner.levelakun'),
        ),
        migrations.AddField(
            model_name='room',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='link',
            field=models.CharField(default='https://zoom.us/', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mastered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Master_of_teacher', to='owner.master'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vocab',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_group', to='teacher.vocabgroup'),
        ),
        migrations.AddField(
            model_name='vocabgroup',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_group_level', to='owner.level'),
        ),
        migrations.AddField(
            model_name='withdrow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_withdrow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='time',
            field=models.IntegerField(blank=True, choices=[(0, '07:30'), (1, '09:00'), (2, '10:30'), (3, '13:00'), (4, '14:30'), (5, '16:00'), (6, '18:30'), (7, '20:00')], default=1),
        ),
        migrations.AddField(
            model_name='schadule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schadule_room', to='teacher.room'),
        ),
    ]
