# Generated by Django 4.2.6 on 2023-10-19 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_schadule_delete_private_delete_usermentor_and_more'),
        ('owner', '0002_langganan_remove_levelakun_ads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('finish', models.BooleanField(default=False)),
                ('like', models.IntegerField(default=0)),
                ('feed', models.CharField(blank=True, max_length=225, null=True)),
                ('feedback', models.CharField(blank=True, max_length=225, null=True)),
                ('enroll', models.BooleanField(default=False)),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='teacher.bab')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_kelas', to='teacher.kelas')),
                ('pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_history_pelajaran', to='teacher.pelajaran')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_course_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_last', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('nilai', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('countdown', models.TimeField(default='00:10:00')),
                ('countdownNow', models.TimeField(default='00:10:00')),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_latihan', to='teacher.bab')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_kelas_latihan', to='teacher.kelas')),
                ('pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_latihan_pelajaran', to='teacher.pelajaran')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_latihan_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('meetremain', models.IntegerField(default=0)),
                ('purchased', models.BooleanField(default=False)),
                ('trx_id', models.IntegerField(default=0)),
                ('via', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('SessionID', models.CharField(max_length=50)),
                ('accountlevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to='owner.levelakun')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_meeting', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to='teacher.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('benar', models.IntegerField(default=0)),
                ('salah', models.IntegerField(default=0)),
                ('isdone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vocab_user', to=settings.AUTH_USER_MODEL)),
                ('vocab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab', to='teacher.vocabgroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserSchadule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadir', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, max_length=225, null=True)),
                ('performance', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to='user.usermeeting')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_room', to='teacher.room')),
                ('schadule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_schadule', to='teacher.schadule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=224)),
                ('photo', models.FileField(default='photo/profile/user.jpg', upload_to='photo/profile')),
                ('join', models.DateField(auto_now_add=True)),
                ('premium_start', models.DateField(blank=True, null=True)),
                ('premium_end', models.DateField(blank=True, null=True)),
                ('xp', models.IntegerField(default=0)),
                ('nyawa', models.IntegerField(default=0)),
                ('game', models.IntegerField(default=0)),
                ('mahkota', models.IntegerField(default=0)),
                ('kelas', models.IntegerField(default=1)),
                ('testi', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=224)),
                ('status', models.IntegerField(choices=[(1, 'user'), (2, 'teacher'), (3, 'owner')], default=1)),
                ('teacher', models.BooleanField(default=False)),
                ('promo', models.BooleanField(default=False)),
                ('level', models.ForeignKey(default='Beginner', on_delete=django.db.models.deletion.CASCADE, related_name='level', to='owner.level', to_field='name')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_akun', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(blank=True, max_length=225, null=True)),
                ('right', models.BooleanField(default=False)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbab_Question', to='teacher.bab')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserQuestion_kelas', to='teacher.kelas')),
                ('latihan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_latihan', to='user.userlatihan')),
                ('questions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserQuestion_Question', to='teacher.questions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMentored', models.BooleanField(default=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('like', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=224)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdone', models.BooleanField(default=False)),
                ('question', models.CharField(blank=True, max_length=225, null=True)),
                ('answer', models.CharField(blank=True, max_length=225, null=True)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bab_kelas_lesson', to='teacher.bab')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_kelas_lesson', to='teacher.kelas')),
                ('pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pelajaran', to='teacher.pelajaran')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_lesson_user', to=settings.AUTH_USER_MODEL)),
                ('userCourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercourse_lesson', to='user.usercourse')),
            ],
        ),
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbab_games', to='teacher.bab')),
                ('games', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usergames_Games', to='teacher.games')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usergames_kelas', to='teacher.kelas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_games_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdone', models.BooleanField(default=False)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbab_bab', to='teacher.bab')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_kelas_bab', to='teacher.kelas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bab_user', to=settings.AUTH_USER_MODEL)),
                ('userCourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercourse_bab', to='user.usercourse')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bukti', models.FileField(blank=True, upload_to='media/bukti')),
                ('approve', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('tgl', models.DateField(auto_now_add=True)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_kelas', to='teacher.kelas')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_promo', to='owner.promo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
